Repository EYBlockchain/nightfall, pull requests merged in 2019-10, with the labels that each got.

#192 Michaelconnor/remove stats json code
  config/.gitignore
  database/src/mappers/user.js
  docker-compose.test.yml
  docker-compose.yml
  integration-test/testData.js
  nightfall_test.log
  offchain/__tests__/pkd-controller.test.js
  offchain/package.json
  offchain/src/pkd-controller.js
  offchain/src/whisper-controller-stub.js
  offchain/src/whisper-controller.js
  zkp-utils/index.js
  zkp/.dockerignore
  zkp/__tests__/f-token-controller.test.js
  zkp/__tests__/nf-token-controller.test.js
  zkp/__tests__/utils.test.js
  zkp/code/config.js
  zkp/package.json
  zkp/src/Element.js
  zkp/src/compute-vectors.js
  zkp/src/config.js
  zkp/src/f-token-controller.js
  zkp/src/f-token-zkp.js
  zkp/src/nf-token-controller.js
  zkp/src/nf-token-zkp.js
  zkp/src/routes/ft-commitment.js
  zkp/src/routes/nft-commitment.js
  zkp/src/vk-controller.js
Labels: ready for review

#184 Refactoring offchain microservice with RPC standards
  api-gateway/src/index.js
  api-gateway/src/rest/offchain.js
  api-gateway/src/routes/user.js
  api-gateway/src/services/api-gateway.js
  offchain/src/index.js
  offchain/src/routes/pkd.js
  offchain/src/routes/whisper.js
  ui/src/app/services/accounts/accounts-api.service.ts
  ui/src/app/services/tokens/token-api.service.ts
  ui/src/app/shared/config.ts
Labels: ready for review

#121 Add zkp module documentation, for #119
  README.md
  zkp/README.md
  zkp/package.json
Labels: changes requested

#207 database microservice api are now follow RESTfull Standards
  api-gateway/src/index.js
  api-gateway/src/middlewares/auth.js
  api-gateway/src/rest/accounts.js
  api-gateway/src/rest/db.js
  api-gateway/src/rest/offchain.js
  api-gateway/src/rest/zkp.js
  api-gateway/src/routes/api-gateway.js
  api-gateway/src/routes/ft-commitment.js
  api-gateway/src/routes/ft.js
  api-gateway/src/routes/nft-commitment.js
  api-gateway/src/routes/nft.js
  api-gateway/src/routes/user.js
  api-gateway/src/services/api-gateway.js
  api-gateway/src/services/ft-commitment.js
  api-gateway/src/services/ft.js
  api-gateway/src/services/nft-commitment.js
  api-gateway/src/services/nft.js
  api-gateway/src/services/whisper.js
  database/src/business/ft-commitment.service.js
  database/src/business/ft.service.js
  database/src/business/index.js
  database/src/business/nft-commitment.service.js
  database/src/business/nft.service.js
  database/src/business/user.service.js
  database/src/common/dbConnections.js
  database/src/index.js
  database/src/mappers/nft-commitment.js
  database/src/mappers/nft.js
  database/src/mappers/user.js
  database/src/middlewares/configure-db-connection.js
  database/src/middlewares/configure-db.js
  database/src/middlewares/response.js
  database/src/models/nft-commitment.model.js
  database/src/routes/accounts.routes.js
  database/src/routes/ft-commitment.routes.js
  database/src/routes/ft.routes.js
  database/src/routes/index.js
  database/src/routes/nft-commitment.routes.js
  database/src/routes/nft.routes.js
  database/src/routes/user.routes.js
  integration-test/test.js
  offchain/src/listeners.js
  offchain/src/rest/api-gateway.js
  ui/src/app/pages/burn-coin/burn-coin.component.ts
  ui/src/app/pages/burn-token/burn-token.component.ts
  ui/src/app/pages/coin-list/coin-list.component.ts
  ui/src/app/pages/login/login.component.ts
  ui/src/app/pages/overview/overview.component.html
  ui/src/app/pages/overview/overview.component.ts
  ui/src/app/pages/spend-coin/spend-coin.component.ts
  ui/src/app/pages/spend-token/spend-token.component.ts
  ui/src/app/pages/token-list/token-list.component.ts
  ui/src/app/services/accounts/accounts-api.service.ts
  ui/src/app/services/coins/coin-api.service.ts
  ui/src/app/services/tokens/token-api.service.ts
  ui/src/app/shared/config.ts
Labels: ready for review

#206 Michaelconnor/one public input
  api-gateway/config/default.js
  api-gateway/src/services/nft.js
  database/src/business/user.service.js
  integration-test/config/test.json
  integration-test/testData.js
  nightfall-test
  nightfall_test.log
  offchain/__tests__/pkd-controller.test.js
  offchain/contracts/PKD.sol
  zkp-utils/index.js
  zkp/__tests__/f-token-controller.test.js
  zkp/__tests__/nf-token-controller.test.js
  zkp/__tests__/utils.test.js
  zkp/code/config.js
  zkp/code/gm17/ft-burn/ft-burn.code
  zkp/code/gm17/ft-mint/ft-mint.code
  zkp/code/gm17/ft-transfer/ft-transfer.code
  zkp/code/gm17/nft-burn/nft-burn.code
  zkp/code/gm17/nft-mint/nft-mint.code
  zkp/code/gm17/nft-transfer/nft-transfer.code
  zkp/code/index.js
  zkp/contracts/FTokenShield.sol
  zkp/contracts/NFTokenShield.sol
  zkp/src/Element.js
  zkp/src/compute-vectors.js
  zkp/src/config.js
  zkp/src/f-token-controller.js
  zkp/src/f-token-zkp.js
  zkp/src/nf-token-controller.js
  zkp/src/nf-token-zkp.js
  zkp/src/routes/ft-commitment.js
  zkp/src/routes/nft-commitment.js
  zkp/src/zokrates.js
Labels: ready for review

#217 Update Nightfall name to not use "the" as consistent with other refer…
  contributing.md
Labels: bug, ready for review

#221 Fix npm package name
  package.json
Labels: bug, ready for review

#218 Fix word styling
  SECURITY.md
Labels: bug, ready for review

#219 feat(doc): add branching and commit message policies
  contributing.md
Labels: enhancement, ready for review

#223 fix: make swap allocation fast, fixes #222
  .github/workflows/test-pull-request.yml
Labels: enhancement

#225 Parallelize test suite
  .github/workflows/test-pull-request.yml
Labels: enhancement

#228 Update Docker permissions documentation
  README.md
Labels: enhancement, ready for review

#234 removed account-utils
  account-utils/account-utils.js
  docker-compose.yml
  install.sh
  offchain/__tests__/pkd-controller.test.js
  offchain/__tests__/whisper-controller-stub.test.js
  offchain/src/index.js
  offchain/src/pkd-controller.js
  offchain/src/web3.js
  offchain/src/whisper-controller.js
  zkp/__tests__/f-token-controller.test.js
  zkp/__tests__/nf-token-controller.test.js
  zkp/__tests__/utils.test.js
  zkp/src/f-token-controller.js
  zkp/src/nf-token-controller.js
  zkp/src/vk-controller.js
  zkp/src/web3.js
Labels: ready for review

#231 nightfall_test.log (integration-test log file) file deleted
  nightfall_test.log
Labels: ready for review

#233 Dependency updates on docker-compose file for api-gateway container
  docker-compose.yml
Labels: ready for review

#209 Refactoring ZKP microservice with RPC standards
  api-gateway/src/index.js
  api-gateway/src/rest/zkp.js
  api-gateway/src/routes/ft-commitment.js
  api-gateway/src/routes/ft.js
  api-gateway/src/routes/nft-commitment.js
  api-gateway/src/routes/nft.js
  api-gateway/src/services/ft.js
  api-gateway/src/services/nft.js
  integration-test/test.js
  offchain/src/rest/api-gateway.js
  ui/src/app/services/accounts/accounts-api.service.ts
  ui/src/app/services/coins/coin-api.service.ts
  ui/src/app/services/tokens/token-api.service.ts
  ui/src/app/shared/config.ts
  zkp/src/index.js
  zkp/src/routes/ft-commitment.js
  zkp/src/routes/ft.js
  zkp/src/routes/nft-commitment.js
  zkp/src/routes/nft.js
Labels: ready for review

#248 api gateway microservice now comply with RPC standards
  api-gateway/package.json
  api-gateway/src/index.js
  api-gateway/src/rest/zkp.js
  api-gateway/src/routes/ft-commitment.js
  api-gateway/src/routes/ft.js
  api-gateway/src/routes/nft-commitment.js
  api-gateway/src/routes/nft.js
  api-gateway/src/routes/shield.js
  api-gateway/src/routes/user.js
  api-gateway/src/services/api-gateway.js
  api-gateway/src/services/ft-commitment.js
  api-gateway/src/services/ft.js
  api-gateway/src/services/nft-commitment.js
  api-gateway/src/services/nft.js
  api-gateway/src/services/shield.js
  integration-test/test.js
  offchain/src/listeners.js
  offchain/src/rest/api-gateway.js
  ui/src/app/pages/user-accounts/user-accounts.component.ts
  ui/src/app/services/accounts/accounts-api.service.ts
  ui/src/app/services/coins/coin-api.service.ts
  ui/src/app/services/tokens/token-api.service.ts
Labels: ready for review

#236 Delete .travis.yml
  .travis.yml
Labels: ready for review

#245 Rename variables for ZKP functions
  zkp/src/f-token-controller.js
  zkp/src/routes/ft-commitment.js
  zkp/src/routes/nft-commitment.js
Labels: ready for review

#240 Refuse to run tested setup if already existing
  nightfall_test.log
Labels: Do Not Merge

#260 take out line "has recipe in makefile"
  zkp/README.md
Labels: ready for review

#255 Rename controller variables
  zkp/src/f-token-controller.js
  zkp/src/nf-token-controller.js
  zkp/src/routes/ft-commitment.js
  zkp/src/routes/nft-commitment.js
Labels: ready for review

#232 configure integration test to use docker-compose.yml file
  .github/workflows/test-pull-request.yml
  Makefile
  accounts/config/test.js
  api-gateway/config/test.js
  database/config/test.js
  docker-compose.test.yml
  docker-entrypoint-initdb.d/01_setup_admin_user.js
  integration-test/config/default.json
  nightfall-test
  offchain/config/test.js
  package.json
  zkp/config/test.js
Labels: ready for review

#266 Westlad/unit test fix
  Makefile
  zkp/README.md
  zkp/__tests__/f-token-controller.test.js
  zkp/__tests__/nf-token-controller.test.js
  zkp/__tests__/utils.test.js
  zkp/package.json
Labels: ready for review

#275 zkp unit tests job for github actions
  .github/workflows/test-pull-request.yml
Labels: ready for review

#258 Pull sc calls into controller (dependent on 255)
  zkp/src/f-token-controller.js
  zkp/src/f-token-zkp.js
  zkp/src/nf-token-controller.js
  zkp/src/nf-token-zkp.js
  zkp/src/routes/ft-commitment.js
  zkp/src/routes/nft-commitment.js
Labels: ready for review
